name: Pulumi TypeScript API Deployment

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - next
  workflow_dispatch:
    branches:
      - main
      - next
jobs:
  pulumiTypescriptAPIDeployment:
    uses: thesparklaboratory/gh-actions-workflows/.github/workflows/pulumi-typescript-api-deploy.yml@main
    with:
      AWS_REGION: us-east-2
      PULUMI_S3_BUCKET: myproject-pulumi
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PULUMI_PASSPHRASE: ${{ secrets.PULUMI_PASSPHRASE }}
